#!/usr/bin/env python3
from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTROL = ROOT / "automation" / "control" / "production.json"
OUTPUT = ROOT / "src" / "automation-control-bundle.generated.ts"
SHA40 = re.compile(r"^[0-9a-f]{40}$")


def git_show(ref: str, path: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(ROOT), "show", f"{ref}:{path}"],
        capture_output=True, text=True, encoding="utf-8", errors="strict", check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"git object unavailable: {ref}:{path}")
    return result.stdout


def build() -> dict[str, dict]:
    control = json.loads(CONTROL.read_text(encoding="utf-8"))
    if control.get("schema_version") != "quantpro-automation-control-v2" or control.get("status") != "PRODUCTION":
        raise RuntimeError("production control schema/status invalid")
    registry = control.get("registry")
    if not isinstance(registry, dict) or not registry:
        raise RuntimeError("production registry missing")
    bundles: dict[str, dict] = {}
    for key, entry in registry.items():
        if not isinstance(entry, dict):
            raise RuntimeError(f"registry entry invalid: {key}")
        ref = entry.get("production_ref")
        prompt_id = entry.get("prompt_id")
        path = entry.get("path")
        scope = entry.get("write_scope")
        if not isinstance(ref, str) or not SHA40.fullmatch(ref):
            raise RuntimeError(f"invalid production_ref: {key}")
        if not all(isinstance(v, str) and v for v in (prompt_id, path, scope)):
            raise RuntimeError(f"invalid prompt contract: {key}")
        prompt = git_show(ref, path)
        head = "\n".join(prompt.splitlines()[:10])
        for token in (f"PROMPT_ID={prompt_id}", "STATUS=PRODUCTION", f"WRITE_SCOPE={scope}"):
            if token not in head:
                raise RuntimeError(f"prompt header mismatch: {key}: {token}")

        def guidance(items: object) -> list[dict[str, str]]:
            if not isinstance(items, list) or not all(isinstance(x, str) and x for x in items):
                raise RuntimeError(f"invalid guidance list: {key}")
            return [{"path": rel, "content": git_show(ref, rel)} for rel in items]

        bundles[key] = {
            "schema_version": "quantpro-automation-bundle-v1",
            "status": "PRODUCTION",
            "registry_key": key,
            "prompt_id": prompt_id,
            "production_ref": ref,
            "write_scope": scope,
            "mode": entry.get("mode"),
            "schedule": entry.get("schedule"),
            "prompt_path": path,
            "prompt": prompt,
            "automation_guidance": guidance(entry.get("automation_guidance", [])),
            "research_guidance": guidance(entry.get("research_guidance", [])),
        }
    return bundles


def write_bundle() -> None:
    bundles = build()
    keys = list(bundles)
    rendered = (
        "// GENERATED by automation/build_runtime_bundle.py. DO NOT EDIT.\n"
        "export const AUTOMATION_REGISTRY_KEYS = " + json.dumps(keys, ensure_ascii=False) + " as const;\n"
        "export const AUTOMATION_CONTROL_BUNDLES = " + json.dumps(bundles, ensure_ascii=False, indent=2) + " as const;\n"
        "export type AutomationRegistryKey = typeof AUTOMATION_REGISTRY_KEYS[number];\n"
    )
    OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"AUTOMATION_RUNTIME_BUNDLE=PASS entries={len(bundles)} output={OUTPUT.name}")


if __name__ == "__main__":
    write_bundle()
